import os
import xml.etree.ElementTree as ET
from xml.dom import minidom

def clean_xml_patterns(xml_path):
    print(f"Processing {xml_path}...")
    tree = ET.parse(xml_path)
    root = tree.getroot()
    
    # Common words to remove
    remove_words = ["股份有限公司", "有限公司", "证券", "营业部", "专用"]
    
    # Common Brokers to separate (Add space after)
    brokers = [
        "中国银河", "国泰君安", "海通", "中信", "华泰", "招商", "国金", "东吴", 
        "兴业", "浙商", "光大", "申万宏源", "东方财富", "方正", "财通", "联储", 
        "华鑫", "开源", "国新", "中金公司", "平安", "瑞银", "摩根大通", "高盛",
        "广发", "东亚前海", "东莞"
    ]
    
    mappings = root.find('SeatMappings')
    for category in mappings.findall('Category'):
        for alias in category.findall('Alias'):
            for branch in alias.findall('Branch'):
                original = branch.text.strip() if branch.text else ""
                
                # Check if it's already "special" pattern (contains space)?
                # Or if it's explicitly set to raw match via previous manual edits
                
                # Logic:
                # 1. Force match="contains"
                branch.set('match', 'contains')
                
                # 2. Clean Text
                new_text = original
                for w in remove_words:
                    new_text = new_text.replace(w, "")
                    
                # 3. Separate Broker and Location
                # Find if it starts with any broker
                matched_broker = None
                for b in brokers:
                    if new_text.startswith(b):
                        matched_broker = b
                        break
                
                if matched_broker:
                    # Check if space already exists?
                    remainder = new_text[len(matched_broker):]
                    if remainder and not remainder.startswith(" "):
                         new_text = f"{matched_broker} {remainder}"
                
                # Special Fixes based on known "typos" or quirks
                if "国泰海通" in new_text:
                    # It's likely "国泰君安" or "海通". 
                    # Row 5: "国泰海通证券北京知春路"
                    # Searched online for "北京知春路": "海通证券...北京知春路".
                    # Let's preserve "知春路" which is unique.
                    # Or just keep it as is, but space separated?
                    # The fuzzy match "国泰海通" won't match "海通".
                    # I should strip "国泰海通" and keep "北京知春路"?
                    # Or correct it to "海通"? 
                    # Let's play safe: Keep "知春路".
                    new_text = new_text.replace("国泰海通", "") # Remove the confusing part
                    # If empty (rare), revert?
                    if not new_text.strip(): new_text = original
                
                # Update text
                branch.text = new_text.strip()
                print(f"  Converted '{original}' -> '{branch.text}'")

    # Save
    rough_string = ET.tostring(root, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    pretty_xml = reparsed.toprettyxml(indent="  ")
    
    # Remove empty lines generated by toprettyxml
    pretty_xml = "\n".join([line for line in pretty_xml.split('\n') if line.strip()])

    with open(xml_path, "w", encoding='utf-8') as f:
        f.write(pretty_xml)
    print("Done.")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    xml_file = os.path.join(base_dir, "data", "lhb_config.xml")
    clean_xml_patterns(xml_file)
